body:
  - type: markdown
    attributes:
      value: |
        **Thanks for helping improve our documentation!** ❤️

        ### ⚠️ Before you submit
        
        This form is for suggesting **structural improvements to our documentation**.
        
        **This is NOT for:**
        - 🆘 In need for support? → [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e). You are more likely to get the answer you are looking for in those places.
        - 📄 Improvements to specific integration documentation → Use the "Provide feedback" or "Edit" button at the bottom of that integration's documentation page
        - ✏️ Fixing typos or small updates → [Edit directly on the docs site](https://www.home-assistant.io/) using the "Edit this page on GitHub" link
        - 🐛 Reporting documentation errors → [Open an issue in the docs repo](https://github.com/home-assistant/home-assistant.io/issues)

  - type: textarea
    id: improvement_description
    attributes:
      label: Describe the improvement
      description: What structural or organizational change would make our documentation better? Include what problems the current structure causes and how you'd improve it.
      placeholder: |
        Example: I'd like to see a "Common Patterns" section that shows typical automation scenarios with full examples. Currently, new users struggle to understand how triggers, conditions, and actions work together because each is documented separately without complete examples. I propose adding a new section with 10-15 complete automation examples, progressing from simple to complex, with explanations of why each part is needed.
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Anything else?
      description: Examples from other projects, specific user groups affected, or offers to help.
      placeholder: |
        Example: The Node-RED documentation has great example-based learning: [link]. I'd be happy to contribute some examples.
    validations:
      required: false