body:
  - type: markdown
    attributes:
      value: |
        **Thanks for suggesting a Matter or Thread enhancement!** ❤️

        ### ⚠️ Before you submit
        
        This form is for requesting **Matter and Thread protocol features or device support**.
        
        **This is NOT for:**
        - 🆘 In need for support? → [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://www.home-assistant.io/join-chat). You are more likely to get the answer you are looking for in those places.
        - 🐛 Reporting Matter/Thread bugs → [Report an issue](https://github.com/home-assistant/core/issues/new/choose)
        - 🔌 Other protocol enhancements → [Use the appropriate protocol category](https://github.com/orgs/home-assistant/discussions/new/choose)

  - type: textarea
    id: enhancement_description
    attributes:
      label: Describe the enhancement
      description: What Matter or Thread feature would you like to see?
      placeholder: |
        Example: I'd like support for Matter-enabled refrigerators like the Samsung Family Hub series. My fridge supports Matter but only shows up as a basic device in Home Assistant. I want to see temperature sensors for different compartments, door open/close sensors, water filter status, and be able to control features like ice maker and water dispenser.
    validations:
      required: true

  - type: textarea
    id: device_information
    attributes:
      label: Device or feature details
      description: Specific devices, Matter device types, or Thread features involved. (optional)
      placeholder: |
        Example: 
        Device: Samsung Family Hub Refrigerator RF28T5001SR
        Matter device type: Refrigerator
        Matter version: 1.0
        Current behavior: Shows up as basic Matter device with no entities
    validations:
      required: false

  - type: textarea
    id: use_cases
    attributes:
      label: Use cases
      description: How would this enhancement improve your smart home?
      placeholder: |
        Example: This would allow me to use my existing Zigbee devices through a Matter bridge without needing a separate Zigbee coordinator.
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Anything else?
      description: Links to Matter specifications, device documentation, or related discussions.
      placeholder: |
        Example: Matter specification section 9.2 describes this feature: [link]
    validations:
      required: false