body:
  - type: markdown
    attributes:
      value: |
        **Thanks for suggesting a Z-Wave enhancement!** ❤️

        ### ⚠️ Before you submit
        
        This form is for requesting **Z-Wave protocol features or device support**.
        
        **This is NOT for:**
        - 🆘 In need for support? → [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://www.home-assistant.io/join-chat). You are more likely to get the answer you are looking for in those places.
        - 🐛 Reporting Z-Wave bugs → [Report an issue](https://github.com/home-assistant/core/issues/new/choose)
        - 🔌 Other protocol enhancements → [Use the appropriate protocol category](https://github.com/orgs/home-assistant/discussions/new/choose)

  - type: textarea
    id: enhancement_description
    attributes:
      label: Describe the enhancement
      description: What Z-Wave feature or device support would you like to see?
      placeholder: |
        Example: I'd like support for Z-Wave Long Range (LR) devices, which offer much better range than traditional Z-Wave.
    validations:
      required: true

  - type: textarea
    id: device_information
    attributes:
      label: Device information
      description: Specific devices, Z-Wave versions, or command classes involved. (optional)
      placeholder: |
        Example: 
        Device: Aeotec Range Extender 7
        Z-Wave version: 700 series with LR support
        Command classes: Basic, Association, Version
    validations:
      required: false

  - type: textarea
    id: use_cases
    attributes:
      label: Use cases
      description: How would this enhancement improve your Z-Wave network?
      placeholder: |
        Example: This would allow me to reach my detached garage without needing multiple repeaters, simplifying my network and improving reliability.
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Anything else?
      description: Links to device documentation, Z-Wave Alliance specs, or technical information.
      placeholder: |
        Example: Z-Wave Alliance device page: [link]
        Device manual with command classes: [link]
    validations:
      required: false